/* ============================================================
   PROJECT: Governed Job Marketplace Semantic Layer
   FILE: 01_environment.sql
   PURPOSE:
     Create the warehouse, database, schemas, and access roles.
   ============================================================ */

USE ROLE ACCOUNTADMIN;

/* ---------- Compute ---------- */

CREATE OR REPLACE WAREHOUSE JOB_MARKETPLACE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Compute for the job marketplace semantic-layer portfolio project';

USE WAREHOUSE JOB_MARKETPLACE_WH;

/* ---------- Database and schemas ---------- */

CREATE OR REPLACE DATABASE JOB_MARKETPLACE
    COMMENT = 'Synthetic job marketplace analytics environment';

CREATE OR REPLACE SCHEMA JOB_MARKETPLACE.RAW
    COMMENT = 'Synthetic source data';

CREATE OR REPLACE SCHEMA JOB_MARKETPLACE.ANALYTICS
    COMMENT = 'Curated dimensional models';

CREATE OR REPLACE SCHEMA JOB_MARKETPLACE.GOVERNANCE
    COMMENT = 'Tags, access mappings, masking policies, and row access policies';

CREATE OR REPLACE SCHEMA JOB_MARKETPLACE.SEMANTIC
    COMMENT = 'Governed Snowflake semantic views';

/* ---------- Roles ---------- */

CREATE OR REPLACE ROLE JOB_MARKETPLACE_SEMANTIC_OWNER
    COMMENT = 'Owns and deploys governed semantic views';

CREATE OR REPLACE ROLE JOB_MARKETPLACE_AMER_ANALYST
    COMMENT = 'Can analyze job performance for AMER markets';

CREATE OR REPLACE ROLE JOB_MARKETPLACE_EMEA_ANALYST
    COMMENT = 'Can analyze job performance for EMEA markets';

CREATE OR REPLACE ROLE JOB_MARKETPLACE_EXECUTIVE
    COMMENT = 'Can analyze all markets and view internal contact information';

/* Grant the roles to the user running this lab. */

SET LAB_USER = CURRENT_USER();

GRANT ROLE JOB_MARKETPLACE_SEMANTIC_OWNER
    TO USER IDENTIFIER($LAB_USER);

GRANT ROLE JOB_MARKETPLACE_AMER_ANALYST
    TO USER IDENTIFIER($LAB_USER);

GRANT ROLE JOB_MARKETPLACE_EMEA_ANALYST
    TO USER IDENTIFIER($LAB_USER);

GRANT ROLE JOB_MARKETPLACE_EXECUTIVE
    TO USER IDENTIFIER($LAB_USER);

/* ---------- Semantic owner permissions ---------- */

GRANT USAGE ON WAREHOUSE JOB_MARKETPLACE_WH
    TO ROLE JOB_MARKETPLACE_SEMANTIC_OWNER;

GRANT USAGE ON DATABASE JOB_MARKETPLACE
    TO ROLE JOB_MARKETPLACE_SEMANTIC_OWNER;

GRANT USAGE ON SCHEMA JOB_MARKETPLACE.ANALYTICS
    TO ROLE JOB_MARKETPLACE_SEMANTIC_OWNER;

GRANT USAGE ON SCHEMA JOB_MARKETPLACE.GOVERNANCE
    TO ROLE JOB_MARKETPLACE_SEMANTIC_OWNER;

GRANT USAGE, CREATE SEMANTIC VIEW
    ON SCHEMA JOB_MARKETPLACE.SEMANTIC
    TO ROLE JOB_MARKETPLACE_SEMANTIC_OWNER;

GRANT SELECT ON FUTURE TABLES
    IN SCHEMA JOB_MARKETPLACE.ANALYTICS
    TO ROLE JOB_MARKETPLACE_SEMANTIC_OWNER;

/* ---------- Consumer permissions ---------- */

GRANT USAGE ON WAREHOUSE JOB_MARKETPLACE_WH
    TO ROLE JOB_MARKETPLACE_AMER_ANALYST;

GRANT USAGE ON WAREHOUSE JOB_MARKETPLACE_WH
    TO ROLE JOB_MARKETPLACE_EMEA_ANALYST;

GRANT USAGE ON WAREHOUSE JOB_MARKETPLACE_WH
    TO ROLE JOB_MARKETPLACE_EXECUTIVE;

GRANT USAGE ON DATABASE JOB_MARKETPLACE
    TO ROLE JOB_MARKETPLACE_AMER_ANALYST;

GRANT USAGE ON DATABASE JOB_MARKETPLACE
    TO ROLE JOB_MARKETPLACE_EMEA_ANALYST;

GRANT USAGE ON DATABASE JOB_MARKETPLACE
    TO ROLE JOB_MARKETPLACE_EXECUTIVE;

GRANT USAGE ON SCHEMA JOB_MARKETPLACE.SEMANTIC
    TO ROLE JOB_MARKETPLACE_AMER_ANALYST;

GRANT USAGE ON SCHEMA JOB_MARKETPLACE.SEMANTIC
    TO ROLE JOB_MARKETPLACE_EMEA_ANALYST;

GRANT USAGE ON SCHEMA JOB_MARKETPLACE.SEMANTIC
    TO ROLE JOB_MARKETPLACE_EXECUTIVE;

/*
Analysts receive access to semantic views, not the underlying tables.
Future grants ensure newly created semantic views are accessible.
*/

GRANT SELECT ON FUTURE SEMANTIC VIEWS
    IN SCHEMA JOB_MARKETPLACE.SEMANTIC
    TO ROLE JOB_MARKETPLACE_AMER_ANALYST;

GRANT SELECT ON FUTURE SEMANTIC VIEWS
    IN SCHEMA JOB_MARKETPLACE.SEMANTIC
    TO ROLE JOB_MARKETPLACE_EMEA_ANALYST;

GRANT SELECT ON FUTURE SEMANTIC VIEWS
    IN SCHEMA JOB_MARKETPLACE.SEMANTIC
    TO ROLE JOB_MARKETPLACE_EXECUTIVE;
