/* ============================================================
   FILE: 03_analytics_models.sql
   PURPOSE:
     Build curated dimensions and the marketplace performance fact.
   ============================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE JOB_MARKETPLACE_WH;
USE DATABASE JOB_MARKETPLACE;
USE SCHEMA ANALYTICS;

/* ---------- Employer dimension ---------- */

CREATE OR REPLACE TABLE DIM_EMPLOYER AS
SELECT
    EMPLOYER_ID,
    EMPLOYER_NAME,
    EMPLOYER_SEGMENT,
    ACCOUNT_REGION,
    ACCOUNT_MANAGER_NAME,
    ACCOUNT_MANAGER_EMAIL,
    CREATED_AT
FROM JOB_MARKETPLACE.RAW.EMPLOYERS;

/* ---------- Job dimension ---------- */

CREATE OR REPLACE TABLE DIM_JOB AS
SELECT
    JOB_ID,
    EMPLOYER_ID,
    JOB_TITLE,
    JOB_CATEGORY,
    COUNTRY_CODE,
    MARKET_REGION,
    SPONSORSHIP_TIER,
    POSTED_DATE,
    CLOSED_DATE,
    IFF(CLOSED_DATE IS NULL, TRUE, FALSE) AS IS_CURRENTLY_OPEN
FROM JOB_MARKETPLACE.RAW.JOBS;

/* ---------- Calendar dimension ---------- */

CREATE OR REPLACE TABLE DIM_DATE AS
WITH DATE_SPINE AS (
    SELECT
        DATEADD(DAY, SEQ4(), '2026-01-01'::DATE) AS DATE_DAY
    FROM TABLE(GENERATOR(ROWCOUNT => 90))
)

SELECT
    DATE_DAY,
    DATE_TRUNC('WEEK', DATE_DAY)::DATE AS WEEK_START,
    DATE_TRUNC('MONTH', DATE_DAY)::DATE AS MONTH_START,
    DATE_TRUNC('QUARTER', DATE_DAY)::DATE AS QUARTER_START,
    YEAR(DATE_DAY) AS CALENDAR_YEAR,
    MONTH(DATE_DAY) AS CALENDAR_MONTH,
    MONTHNAME(DATE_DAY) AS MONTH_NAME,
    TO_CHAR(DATE_DAY, 'YYYY-MM') AS YEAR_MONTH,
    DAYNAME(DATE_DAY) AS DAY_NAME
FROM DATE_SPINE;

/* ---------- Daily marketplace performance fact ---------- */

CREATE OR REPLACE TABLE FCT_JOB_PERFORMANCE_DAILY AS
SELECT
    P.EVENT_DATE,
    P.JOB_ID,
    P.MARKET_REGION,
    P.DEVICE_TYPE,
    P.TRAFFIC_SOURCE,
    P.IMPRESSIONS,
    P.CLICKS,
    P.APPLICATIONS,
    P.QUALIFIED_APPLICATIONS,
    P.HIRES,
    P.SPONSORED_SPEND_USD,
    P.LOADED_AT
FROM JOB_MARKETPLACE.RAW.JOB_PERFORMANCE_DAILY P;
