/* ============================================================
   FILE: 04_data_quality_tests.sql
   PURPOSE:
     Validate grain, referential integrity, and funnel logic.
   ============================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE JOB_MARKETPLACE_WH;
USE DATABASE JOB_MARKETPLACE;

/* Test 1: Expected fact count */

SELECT
    'EXPECTED_FACT_ROW_COUNT' AS TEST_NAME,
    IFF(COUNT(*) = 3204, 'PASS', 'FAIL') AS TEST_RESULT,
    COUNT(*) AS ACTUAL_VALUE,
    3204 AS EXPECTED_VALUE
FROM ANALYTICS.FCT_JOB_PERFORMANCE_DAILY;

/* Test 2: Fact grain must be unique */

SELECT
    'UNIQUE_FACT_GRAIN' AS TEST_NAME,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS TEST_RESULT,
    COUNT(*) AS INVALID_GROUPS
FROM (
    SELECT
        EVENT_DATE,
        JOB_ID,
        DEVICE_TYPE,
        TRAFFIC_SOURCE
    FROM ANALYTICS.FCT_JOB_PERFORMANCE_DAILY
    GROUP BY
        EVENT_DATE,
        JOB_ID,
        DEVICE_TYPE,
        TRAFFIC_SOURCE
    HAVING COUNT(*) > 1
);

/* Test 3: Every fact row must match a job */

SELECT
    'NO_ORPHAN_JOBS' AS TEST_NAME,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS TEST_RESULT,
    COUNT(*) AS ORPHAN_ROWS
FROM ANALYTICS.FCT_JOB_PERFORMANCE_DAILY F

LEFT JOIN ANALYTICS.DIM_JOB J
    ON F.JOB_ID = J.JOB_ID

WHERE J.JOB_ID IS NULL;

/* Test 4: Every fact row must match a calendar date */

SELECT
    'NO_ORPHAN_DATES' AS TEST_NAME,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS TEST_RESULT,
    COUNT(*) AS ORPHAN_ROWS
FROM ANALYTICS.FCT_JOB_PERFORMANCE_DAILY F

LEFT JOIN ANALYTICS.DIM_DATE D
    ON F.EVENT_DATE = D.DATE_DAY

WHERE D.DATE_DAY IS NULL;

/* Test 5: Funnel stages cannot increase downstream */

SELECT
    'VALID_FUNNEL_SEQUENCE' AS TEST_NAME,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS TEST_RESULT,
    COUNT(*) AS INVALID_ROWS
FROM ANALYTICS.FCT_JOB_PERFORMANCE_DAILY
WHERE
       CLICKS > IMPRESSIONS
    OR APPLICATIONS > CLICKS
    OR QUALIFIED_APPLICATIONS > APPLICATIONS
    OR HIRES > QUALIFIED_APPLICATIONS;

/* Test 6: Only sponsored traffic may have spend */

SELECT
    'SPONSORED_SPEND_RULE' AS TEST_NAME,
    IFF(COUNT(*) = 0, 'PASS', 'FAIL') AS TEST_RESULT,
    COUNT(*) AS INVALID_ROWS
FROM ANALYTICS.FCT_JOB_PERFORMANCE_DAILY
WHERE
    TRAFFIC_SOURCE <> 'SPONSORED'
    AND SPONSORED_SPEND_USD <> 0;

/* Test 7: Inspect baseline totals */

SELECT
    SUM(IMPRESSIONS) AS IMPRESSIONS,
    SUM(CLICKS) AS CLICKS,
    SUM(APPLICATIONS) AS APPLICATIONS,
    SUM(QUALIFIED_APPLICATIONS) AS QUALIFIED_APPLICATIONS,
    SUM(HIRES) AS HIRES,
    SUM(SPONSORED_SPEND_USD) AS SPONSORED_SPEND_USD
FROM ANALYTICS.FCT_JOB_PERFORMANCE_DAILY;
