/* ============================================================
   FILE: 05_governance.sql
   PURPOSE:
     Implement metric tags, regional row access, and masking.
   ============================================================ */

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE JOB_MARKETPLACE_WH;
USE DATABASE JOB_MARKETPLACE;
USE SCHEMA GOVERNANCE;

/* ---------- Governance tags ---------- */

CREATE OR REPLACE TAG DATA_CLASSIFICATION
    ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL'
    COMMENT = 'Classification of marketplace data';

CREATE OR REPLACE TAG DATA_DOMAIN
    ALLOWED_VALUES 'JOB_MARKETPLACE'
    COMMENT = 'Business domain represented by an object';

CREATE OR REPLACE TAG METRIC_TIER
    ALLOWED_VALUES 'CERTIFIED', 'EXPERIMENTAL'
    COMMENT = 'Governance status of a business metric';

/* Permit the semantic owner to use these tags in the semantic view. */

GRANT APPLY
    ON TAG JOB_MARKETPLACE.GOVERNANCE.DATA_CLASSIFICATION
    TO ROLE JOB_MARKETPLACE_SEMANTIC_OWNER;

GRANT APPLY
    ON TAG JOB_MARKETPLACE.GOVERNANCE.DATA_DOMAIN
    TO ROLE JOB_MARKETPLACE_SEMANTIC_OWNER;

GRANT APPLY
    ON TAG JOB_MARKETPLACE.GOVERNANCE.METRIC_TIER
    TO ROLE JOB_MARKETPLACE_SEMANTIC_OWNER;

/* Tag the sensitive physical column. */

ALTER TABLE JOB_MARKETPLACE.ANALYTICS.DIM_EMPLOYER
    MODIFY COLUMN ACCOUNT_MANAGER_EMAIL
    SET TAG JOB_MARKETPLACE.GOVERNANCE.DATA_CLASSIFICATION
        = 'CONFIDENTIAL';

/* ---------- Regional role mapping ---------- */

CREATE OR REPLACE TABLE REGION_ROLE_ACCESS (
    ROLE_NAME      VARCHAR NOT NULL,
    MARKET_REGION  VARCHAR NOT NULL
);

INSERT INTO REGION_ROLE_ACCESS
VALUES
    ('JOB_MARKETPLACE_AMER_ANALYST', 'AMER'),
    ('JOB_MARKETPLACE_EMEA_ANALYST', 'EMEA'),
    ('JOB_MARKETPLACE_EXECUTIVE',    'ALL');

/* ---------- Row-access policy ---------- */

CREATE OR REPLACE ROW ACCESS POLICY RAP_MARKET_REGION
AS (ROW_MARKET_REGION VARCHAR)
RETURNS BOOLEAN ->
       CURRENT_ROLE() IN (
           'ACCOUNTADMIN',
           'JOB_MARKETPLACE_SEMANTIC_OWNER'
       )

    OR EXISTS (
        SELECT 1
        FROM JOB_MARKETPLACE.GOVERNANCE.REGION_ROLE_ACCESS A
        WHERE A.ROLE_NAME = CURRENT_ROLE()
          AND (
                 A.MARKET_REGION = ROW_MARKET_REGION
              OR A.MARKET_REGION = 'ALL'
          )
    );

/*
Apply the policy to both:
1. The fact table, to protect metric results.
2. The job dimension, to protect dimension-only queries.
*/

ALTER TABLE JOB_MARKETPLACE.ANALYTICS.FCT_JOB_PERFORMANCE_DAILY
    ADD ROW ACCESS POLICY
        JOB_MARKETPLACE.GOVERNANCE.RAP_MARKET_REGION
    ON (MARKET_REGION);

ALTER TABLE JOB_MARKETPLACE.ANALYTICS.DIM_JOB
    ADD ROW ACCESS POLICY
        JOB_MARKETPLACE.GOVERNANCE.RAP_MARKET_REGION
    ON (MARKET_REGION);

/* ---------- Masking policy ---------- */

CREATE OR REPLACE MASKING POLICY MP_INTERNAL_EMAIL
AS (VALUE VARCHAR)
RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN (
            'ACCOUNTADMIN',
            'JOB_MARKETPLACE_SEMANTIC_OWNER',
            'JOB_MARKETPLACE_EXECUTIVE'
        )
            THEN VALUE

        ELSE REGEXP_REPLACE(
            VALUE,
            '^[^@]+',
            '***'
        )
    END;

ALTER TABLE JOB_MARKETPLACE.ANALYTICS.DIM_EMPLOYER
    MODIFY COLUMN ACCOUNT_MANAGER_EMAIL
    SET MASKING POLICY
        JOB_MARKETPLACE.GOVERNANCE.MP_INTERNAL_EMAIL;
