USE ROLE JOB_MARKETPLACE_SEMANTIC_OWNER;
USE WAREHOUSE JOB_MARKETPLACE_WH;
USE DATABASE JOB_MARKETPLACE;
USE SCHEMA SEMANTIC;

/* Inspect all semantic object properties. */

DESC SEMANTIC VIEW JOB_MARKETPLACE_PERFORMANCE;

/* List certified metrics. */

SHOW SEMANTIC METRICS
    IN JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE;

/* List dimensions. */

SHOW SEMANTIC DIMENSIONS
    IN JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE;

/*
Confirm which dimensions Snowflake considers compatible
with the total_applications metric.
*/

SHOW SEMANTIC DIMENSIONS
    IN JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE
    FOR METRIC TOTAL_APPLICATIONS;

/* Export the deployed DDL for version comparison. */

SELECT GET_DDL(
    'SEMANTIC_VIEW',
    'JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE'
);

/* Export the semantic view as YAML. */

SELECT SYSTEM$READ_YAML_FROM_SEMANTIC_VIEW(
    'JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE'
);

-- Query 1: Overall marketplace totals

SELECT *
FROM SEMANTIC_VIEW(
    JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE

    METRICS
        PERFORMANCE.ACTIVE_JOB_COUNT,
        PERFORMANCE.TOTAL_IMPRESSIONS,
        PERFORMANCE.TOTAL_CLICKS,
        PERFORMANCE.TOTAL_APPLICATIONS,
        PERFORMANCE.TOTAL_QUALIFIED_APPLICATIONS,
        PERFORMANCE.TOTAL_HIRES,
        PERFORMANCE.CLICK_THROUGH_RATE,
        PERFORMANCE.APPLY_RATE,
        PERFORMANCE.QUALIFIED_APPLICATION_RATE
);

-- Query 2: Monthly performance by market

SELECT *
FROM SEMANTIC_VIEW(
    JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE

    DIMENSIONS
        CALENDAR.MONTH_START,
        JOBS.MARKET_REGION

    METRICS
        PERFORMANCE.ACTIVE_JOB_COUNT,
        PERFORMANCE.TOTAL_IMPRESSIONS,
        PERFORMANCE.TOTAL_CLICKS,
        PERFORMANCE.TOTAL_APPLICATIONS,
        PERFORMANCE.APPLY_RATE
)
ORDER BY
    MONTH_START,
    MARKET_REGION;

-- Query 3: Employer funnel performance

SELECT *
FROM SEMANTIC_VIEW(
    JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE

    DIMENSIONS
        EMPLOYERS.EMPLOYER_NAME,
        EMPLOYERS.EMPLOYER_SEGMENT

    METRICS
        PERFORMANCE.ACTIVE_JOB_COUNT,
        PERFORMANCE.TOTAL_IMPRESSIONS,
        PERFORMANCE.TOTAL_APPLICATIONS,
        PERFORMANCE.TOTAL_QUALIFIED_APPLICATIONS,
        PERFORMANCE.TOTAL_HIRES
)
ORDER BY TOTAL_APPLICATIONS DESC;

-- Query 4: Sponsored efficiency

SELECT *
FROM SEMANTIC_VIEW(
    JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE

    DIMENSIONS
        JOBS.SPONSORSHIP_TIER,
        PERFORMANCE.TRAFFIC_SOURCE

    METRICS
        PERFORMANCE.TOTAL_SPONSORED_SPEND_USD,
        PERFORMANCE.TOTAL_APPLICATIONS,
        PERFORMANCE.TOTAL_QUALIFIED_APPLICATIONS,
        PERFORMANCE.COST_PER_APPLICATION,
        PERFORMANCE.COST_PER_QUALIFIED_APPLICATION
)
ORDER BY
    TOTAL_SPONSORED_SPEND_USD DESC;

-- Query 5: Device comparison

SELECT *
FROM SEMANTIC_VIEW(
    JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE

    DIMENSIONS
        PERFORMANCE.DEVICE_TYPE

    METRICS
        PERFORMANCE.TOTAL_IMPRESSIONS,
        PERFORMANCE.TOTAL_CLICKS,
        PERFORMANCE.TOTAL_APPLICATIONS,
        PERFORMANCE.CLICK_THROUGH_RATE,
        PERFORMANCE.APPLY_RATE
)
ORDER BY TOTAL_APPLICATIONS DESC;

-- Query 6: Standard SQL syntax

SELECT
    MARKET_REGION,
    AGG(TOTAL_IMPRESSIONS) AS TOTAL_IMPRESSIONS,
    AGG(TOTAL_APPLICATIONS) AS TOTAL_APPLICATIONS,
    AGG(APPLY_RATE) AS APPLY_RATE
FROM JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE
GROUP BY MARKET_REGION
ORDER BY TOTAL_APPLICATIONS DESC;


-- 11. Compare the semantic layer with raw SQL

USE ROLE JOB_MARKETPLACE_SEMANTIC_OWNER;

/* ---------- Physical calculation ---------- */

WITH PHYSICAL_RESULTS AS (
    SELECT
        DATE_TRUNC('MONTH', F.EVENT_DATE)::DATE AS MONTH_START,
        J.MARKET_REGION,
        SUM(F.IMPRESSIONS) AS TOTAL_IMPRESSIONS,
        SUM(F.CLICKS) AS TOTAL_CLICKS,
        SUM(F.APPLICATIONS) AS TOTAL_APPLICATIONS,
        SUM(F.APPLICATIONS)
            / NULLIF(SUM(F.CLICKS), 0) AS APPLY_RATE
    FROM JOB_MARKETPLACE.ANALYTICS.FCT_JOB_PERFORMANCE_DAILY F

    INNER JOIN JOB_MARKETPLACE.ANALYTICS.DIM_JOB J
        ON F.JOB_ID = J.JOB_ID

    GROUP BY
        DATE_TRUNC('MONTH', F.EVENT_DATE)::DATE,
        J.MARKET_REGION
),

/* ---------- Semantic calculation ---------- */

SEMANTIC_RESULTS AS (
    SELECT *
    FROM SEMANTIC_VIEW(
        JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE

        DIMENSIONS
            CALENDAR.MONTH_START,
            JOBS.MARKET_REGION

        METRICS
            PERFORMANCE.TOTAL_IMPRESSIONS,
            PERFORMANCE.TOTAL_CLICKS,
            PERFORMANCE.TOTAL_APPLICATIONS,
            PERFORMANCE.APPLY_RATE
    )
)

/* ---------- Compare results ---------- */

SELECT
    COALESCE(P.MONTH_START, S.MONTH_START) AS MONTH_START,
    COALESCE(P.MARKET_REGION, S.MARKET_REGION) AS MARKET_REGION,

    P.TOTAL_IMPRESSIONS AS PHYSICAL_IMPRESSIONS,
    S.TOTAL_IMPRESSIONS AS SEMANTIC_IMPRESSIONS,

    P.TOTAL_APPLICATIONS AS PHYSICAL_APPLICATIONS,
    S.TOTAL_APPLICATIONS AS SEMANTIC_APPLICATIONS,

    P.APPLY_RATE AS PHYSICAL_APPLY_RATE,
    S.APPLY_RATE AS SEMANTIC_APPLY_RATE,

    CASE
        WHEN P.TOTAL_IMPRESSIONS = S.TOTAL_IMPRESSIONS
         AND P.TOTAL_CLICKS = S.TOTAL_CLICKS
         AND P.TOTAL_APPLICATIONS = S.TOTAL_APPLICATIONS
         AND ABS(P.APPLY_RATE - S.APPLY_RATE) < 0.000001
            THEN 'PASS'
        ELSE 'FAIL'
    END AS RECONCILIATION_RESULT

FROM PHYSICAL_RESULTS P

FULL OUTER JOIN SEMANTIC_RESULTS S
    ON P.MONTH_START = S.MONTH_START
   AND P.MARKET_REGION = S.MARKET_REGION

ORDER BY
    MONTH_START,
    MARKET_REGION;
