-- 12. Test the AMER analyst role

USE ROLE JOB_MARKETPLACE_AMER_ANALYST;
USE WAREHOUSE JOB_MARKETPLACE_WH;

/*
Expected:
Only AMER should be returned.
*/

SELECT *
FROM SEMANTIC_VIEW(
    JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE

    DIMENSIONS
        JOBS.MARKET_REGION

    METRICS
        PERFORMANCE.TOTAL_APPLICATIONS
);

-- Test the masked email:

SELECT *
FROM SEMANTIC_VIEW(
    JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE

    DIMENSIONS
        EMPLOYERS.EMPLOYER_NAME,
        EMPLOYERS.ACCOUNT_MANAGER_EMAIL

    METRICS
        PERFORMANCE.TOTAL_APPLICATIONS
)
ORDER BY EMPLOYER_NAME;

-- Confirm that the role cannot query the base fact directly:

SELECT *
FROM JOB_MARKETPLACE.ANALYTICS.FCT_JOB_PERFORMANCE_DAILY
LIMIT 10;

-- 13. Test the EMEA analyst role

USE ROLE JOB_MARKETPLACE_EMEA_ANALYST;
USE WAREHOUSE JOB_MARKETPLACE_WH;

SELECT *
FROM SEMANTIC_VIEW(
    JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE

    DIMENSIONS
        JOBS.MARKET_REGION

    METRICS
        PERFORMANCE.TOTAL_APPLICATIONS
);

-- The email test should still return masked values:

SELECT *
FROM SEMANTIC_VIEW(
    JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE

    DIMENSIONS
        EMPLOYERS.EMPLOYER_NAME,
        EMPLOYERS.ACCOUNT_MANAGER_EMAIL

    METRICS
        PERFORMANCE.TOTAL_APPLICATIONS
);

-- 14. Test the executive role

USE ROLE JOB_MARKETPLACE_EXECUTIVE;
USE WAREHOUSE JOB_MARKETPLACE_WH;

SELECT *
FROM SEMANTIC_VIEW(
    JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE

    DIMENSIONS
        JOBS.MARKET_REGION

    METRICS
        PERFORMANCE.TOTAL_APPLICATIONS
)
ORDER BY MARKET_REGION;

-- Test unmasked contact information:

SELECT *
FROM SEMANTIC_VIEW(
    JOB_MARKETPLACE.SEMANTIC.JOB_MARKETPLACE_PERFORMANCE

    DIMENSIONS
        EMPLOYERS.EMPLOYER_NAME,
        EMPLOYERS.ACCOUNT_MANAGER_EMAIL

    METRICS
        PERFORMANCE.TOTAL_APPLICATIONS
)
ORDER BY EMPLOYER_NAME;
